#!/usr/bin/env bash
set -euo pipefail

echo "== Development container tool versions =="
printf "%-16s %s\n" "Git" "$(git --version)"
printf "%-16s %s\n" "GitHub CLI" "$(gh --version | head -n 1)"
printf "%-16s %s\n" "AWS CLI" "$(aws --version 2>&1)"
printf "%-16s %s\n" "Python" "$(python3 --version)"
printf "%-16s %s\n" "pip" "$(pip3 --version)"
printf "%-16s %s\n" "Node.js" "$(node --version)"
printf "%-16s %s\n" "npm" "$(npm --version)"
printf "%-16s %s\n" "Go" "$(go version)"
printf "%-16s %s\n" "Terraform" "$(terraform version | head -n 1)"
printf "%-16s %s\n" "OpenTofu" "$(tofu version | head -n 1)"
printf "%-16s %s\n" "kubectl" "$(kubectl version --client --output=yaml | awk '/gitVersion:/ {print $2; exit}')"
printf "%-16s %s\n" "Helm" "$(helm version --short)"
printf "%-16s %s\n" "jq" "$(jq --version)"
printf "%-16s %s\n" "yq" "$(yq --version)"
printf "%-16s %s\n" "make" "$(make --version | head -n 1)"
printf "%-16s %s\n" "Newman" "$(newman --version)"
printf "%-16s %s\n" "SSM Plugin" "$(session-manager-plugin --version 2>&1 || echo 'not found')"
printf "%-16s %s\n" "Ruff" "$(ruff --version)"
printf "%-16s %s\n" "ESLint" "$(eslint --version)"
printf "%-16s %s\n" "golangci-lint" "$(golangci-lint --version 2>&1 | awk '{print $4}')"
printf "%-16s %s\n" "Claude Code" "$(claude --version)"
